@LMS.API_HostAddress = https://localhost:7080

GET {{LMS.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LMS.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "UserName":"Test",
  "Password" : "Got!22!"
}

###

POST {{LMS.API_HostAddress}}/api/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWF6ZW4yMkVsbmVtcyIsImp0aSI6IjAwZTA4MTliLTIwZWEtNDJhNS1hYzk4LThkMmNjM2Q2YjQ1MiIsInVpZCI6IjMiLCJyb2xlcyI6IkFkbWluIiwiZXhwIjoxNzYwODA0MDcwLCJpc3MiOiJMTVMuQVBJIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.JyVGkzc-W3ZPCU5Rae7_cseUG3Bk-e6IbRBAxEIlFyE

{
  "userName": "MohamedSheki",
  "fullName": "MohamedHamed",
  "password": "Mohamed22!",
  "confirmPassword": "Mohamed22!",
  "role": "Student"
}

###
